# Drawer makefile
# mingw32-make to make things

CXXFLAGS=-O2 -Wall -Wextra
LDFLAGS=-lSDL2main -lSDL2 -mwindows

all : funcbitmap waves julia

julia : julia.cc sdlutil.o
	${CXX} julia.cc sdlutil.o ${CXXFLAGS} ${LDFLAGS} -o $@

waves : waves.cc sdlutil.o
	${CXX} waves.cc sdlutil.o ${CXXFLAGS} ${LDFLAGS} -o $@

funcbitmap : funcbitmap.cc sdlutil.o
	${CXX} funcbitmap.cc sdlutil.o ${CXXFLAGS} ${LDFLAGS} -o $@

sdlutil.o : sdlutil.cc sdlutil.hpp

.PHONY: clean
clean:
	del *.exe *.o *.bmp
